image: docker:19.03.13

services:
  - docker:19.03.13-dind

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image_base:
  only:
    - /.*-build/
  stage: build
  allow_failure: false
  script:
    - export IMAGE_NAME=${CI_COMMIT_REF_NAME%-*}
    - docker pull $CI_REGISTRY_IMAGE:testing || true
    - docker build -f docker/php/Dockerfile --cache-from $CI_REGISTRY_IMAGE:testing -t $CI_REGISTRY_IMAGE:${IMAGE_NAME} -t $CI_REGISTRY_IMAGE:testing .
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_NAME}
    - docker push $CI_REGISTRY_IMAGE:test
