image: docker:19.03.13

services:
  - docker:19.03.13-dind

stages:
  - build

before_script:
  - docker login registry.gitlab.com -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image_base:
  only:
    - /.*-build/
  stage: build
  allow_failure: false
  script:
    - export IMAGE_NAME=${CI_COMMIT_REF_NAME%-*}
    - docker pull $CI_REGISTRY_IMAGE:test || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:test -t $CI_REGISTRY_IMAGE:${IMAGE_NAME} -t $CI_REGISTRY_IMAGE:test
    - docker push $CI_REGISTRY_IMAGE:${IMAGE_NAME}
    - docker push $CI_REGISTRY_IMAGE:test