image: docker:19.03.13

services:
  - docker:19.03.13-dind

stages:
  - build

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $CI_REGISTRY

build_image_base:
  only:
    - /.*-build/
  stage: build
  allow_failure: false
  script:
    - export REF_NAME=${CI_COMMIT_REF_NAME%-*}
    - export REGISTRY_IMAGE=${CI_REGISTRY_IMAGE}/backoffice
    - export VERSION_DUMP=$(echo `git branch --show-current` "(build "`date +'%Y%m%d%H%M%S'`")")
    - docker pull ${REGISTRY_IMAGE}:testing || true
    - echo $VERSION_DUMP > VERSION
    - docker build -f docker/php/Dockerfile --cache-from ${REGISTRY_IMAGE}:testing -t ${REGISTRY_IMAGE}:${REF_NAME} -t ${REGISTRY_IMAGE}:testing .
    - docker push ${REGISTRY_IMAGE}:${REF_NAME}
    - docker push ${REGISTRY_IMAGE}:testing
