version: "3"

services:
  admin:
    image: nginx:alpine
    restart: "no"
    ports:
      - 9000:80
    volumes:
      - ./:/var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - php_back
      - database
      - mailhog

  php_back:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: "always"
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    extra_hosts:
      - sadaic.org.ar:10.30.110.20
      - www.sadaic.org.ar:10.30.110.20

  database:
    image: mariadb
    restart: "no"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: backoffice
      MYSQL_USER: backoffice
      MYSQL_PASSWORD: backoffice

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - app-network

  adminer:
    image: adminer
    restart: "no"
    ports:
      - 8306:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: database
    volumes:
      - ./docker/adminer/php.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    name: registro-obras_dbdata
    external: true