version: "3.8"

services:

  nginx_backoffice:
    restart: "always"
    volumes:
      - type: volume
        source: code-backoffice
        target: /var/www
        volume:
          nocopy: true
      - user-files:/var/www/storage/app/files
      - sync-files:/var/www/storage/app/sadaic
    env_file:
      - .env
    ports:
      - 9443:8443
      - 9000:8000

  nginx_registro_obras:
    restart: "always"
    volumes:
      - type: volume
        source: code-registro-obras
        target: /var/www
        volume:
          nocopy: true
      - user-files:/var/www/storage/app/files
    env_file:
      - ../registro-obras/.env
    ports:
      - 8443:8443
      - 8000:8000

  php_backoffice:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: "always"
    volumes:
      - code-backoffice:/var/www
    env_file:
      - .env

  php_registro_obras:
    build:
      context: ../registro-obras
      dockerfile: ../registro-obras/docker/Dockerfile
    restart: "always"
    volumes:
      - code-registro-obras:/var/www
    env_file:
      - ../registro-obras/.env

volumes:
  code-backoffice:
  code-registro-obras:
  user-files:
  sync-files: