version: "3.8"

services:

  nginx:
    image: nginx:1.19-alpine
    restart: "no"
    volumes:
      - type: volume
        source: code-registro-obras
        target: /var/www/registro-obras
        volume:
          nocopy: true
      - type: volume
        source: code-backoffice
        target: /var/www/backoffice
        volume:
          nocopy: true
    networks:
      - app-network
    depends_on:
      - php_backoffice
      - database

  php_backoffice:
    image: registry.gitlab.com/qkstudio/sadaic/registro-obras/backoffice:latest
    restart: "always"
    networks:
      - app-network
    volumes:
      - code-backoffice:/var/www
      - user-files:/var/www/storage/app/files

  php_registro_obras:
    image: registry.gitlab.com/qkstudio/sadaic/registro-obras:latest
    restart: "always"
    networks:
      - app-network
    volumes:
      - code-registro-obras:/var/www
      - user-files:/var/www/storage/app/files

  database:
    image: mariadb:10.5.6-focal
    restart: "no"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-toor}

networks:
  app-network:
    driver: bridge

volumes:
  code-backoffice:
  code-registro-obras:
  user-files:
  dbdata:
