version: "3.8"

services:

  nginx_backoffice:
    restart: "always"
    volumes:
      - ./src/public:/var/www/public
    env_file:
      - .env
    ports:
      - 9443:8443
      - 9000:8000

  nginx_registro_obras:
    restart: "always"
    volumes:
      - ../registro-obras/src/public:/var/www/public
    env_file:
      - ../registro-obras/.env
    ports:
      - 8443:8443
      - 8000:8000

  php_backoffice:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: "always"
    volumes:
      - ./src:/var/www
    env_file:
      - .env

  php_registro_obras:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: "always"
    volumes:
      - ../registro-obras/src:/var/www
    env_file:
      - ../registro-obras/.env