version: "3.8"

services:
  nginx:
    depends_on:
      - php_back
      - database
      - mailhog

  php_back:
    build:
      context: .
      args:
        - DEV
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: "no"
    ports:
      - 8025:8025
    networks:
      - app-network

  adminer:
    image: adminer:4.7.7
    restart: "no"
    ports:
      - 8306:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER:-database}
    volumes:
      - ./docker/adminer/php.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
    networks:
      - app-network