version: "3.8"

services:

  nginx_backoffice:
    restart: "always"
    volumes:
      - ./src/public:/var/www/public
    env_file:
      - .env

  nginx_registro_obras:
    restart: "always"
    volumes:
      - ../registro-obras/src/public:/var/www/public
    env_file:
      - ../registro-obras/.env

  php_backoffice:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: "always"
    volumes:
      - ./src:/var/www
    env_file:
      - .env

  php_registro_obras:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: "always"
    volumes:
      - ../registro-obras/src:/var/www
    env_file:
      - ../registro-obras/.env