version: "3.8"

services:

  nginx:
    env_file:
      - .env

  php_backoffice:
    env_file:
      - .env

  php_registro_obras:
    env_file:
      - ../registro-obras/.env

  database:
    env_file:
      - .env