version: "3"

services:
  nginx:
    image: nginx:1.19-alpine
    restart: "no"
    ports:
      - 9000:80
    volumes:
      - src/:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
    depends_on:
      - php_back
      - database
      - mailhog

  php_back:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: "always"
    volumes:
      - src/:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    extra_hosts:
      - sadaic.org.ar:10.30.110.20
      - www.sadaic.org.ar:10.30.110.20

  database:
    image: mariadb:10.5.6-focal
    restart: "no"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025
    networks:
      - app-network

  adminer:
    image: adminer:4.7.7
    restart: "no"
    ports:
      - 8306:8080
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_SERVER: ${ADMINER_DEFAULT_SERVER}
    volumes:
      - ./docker/adminer/php.ini:/usr/local/etc/php/conf.d/0-upload_large_dumps.ini
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    name: sadaic-network

volumes:
  dbdata:
    name: sadaic-dbdata