#!/bin/sh
# Listado de localidades y provincias: DIV_ADMINISTRATIVAS.csv
# Listado de géneros: DOC_MW_REF_INT_GENRE.csv
# Listado de países: PAISES TIS_N.csv
# Listado de roles de los derechohabientes: REF_MW_WORK_ROLE.csv
# Listado de otras sociedades: REF_SOCIETY.csv
# Listado de socios: SOCIOS SGS Completo.csv
# Listado de tipos de documento: Tipos Documentos.csv
# Listado de productoras y agencias: DATOS_USUARIOS.csv
# Salida de SGS: *.json

cd /home/Web-registro-obras/sync/input

ftp -ivn <<EOJ >> /tmp/some_log_file
open 10.26.110.19
user web desarrollo2021
asc
dir A0* /tmp/A0.lst
quit
EOJ

echo "open 10.26.110.19" >> /tmp/batch.out
echo "user web desarrollo2021" >> /tmp/batch.out

awk '{print $NF}' /tmp/A0.lst | while read file; do
echo "get $file" >> /tmp/batch.out
echo "del $file" >> /tmp/batch.out
done
echo "bye" >> /tmp/batch.out
rm /tmp/A0.lst
ftp -ivn < /tmp/batch.out >> /tmp/sadaic-sync

cd /home/Web-registro-obras/backoffice/scripts